import imgVenishkumar from "./images/venishkumar.jpg";
import imgMathavan from "./images/Mathavan.jpg";
import imgIdhayachandran from "./images/idhayachandran.jpg";
import imgPrathap from "./images/prathap.jpg";
import imgPradeepKumar from "./images/pradeepkumar.jpg";
import imgTamilSelvi from "./images/tamilselvi.jpg";
import imgShanthaDevi from "./images/shanthadevi.jpg";
import imgGowthami from "./images/gowthami.jpg";
import imgBharathiKannan from "./images/bharathikannan.jpg";

export const electronicsFacultyData = [
  {
    id: "hod",
    slug: "dr-t-venishkumar",
    name: "Dr. T. Venishkumar",
    desig: "Professor & Head [I/C]",
    qual: "B.E - ECE, M.E - VLSI Design, Ph.D",
    email: "tvenishkumar@gmail.com",
    image: imgVenishkumar,
    spec: "Digital VLSI, Device Modeling, Analog VLSI",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-t-venish-kumar-thangaraj-me-ph-d-59533218",
    about: "Dr. T. Venish Kumar serves as the Head of the Department of Electronics and Communication Engineering with 15 years of teaching and research experience. His areas of specialization include Digital VLSI, Device Modeling, and Analog VLSI. With extensive contributions in research, patents, and funded projects, he is committed to academic excellence, innovation, and preparing students for the evolving semiconductor and electronics industry.",
    publications: ["20"],
    projects: ["3"],
    patents: ["4"],
    awards: [],
    experience: ["15 Years"]
  },
  {
    id: "dr-n-mathavan",
    slug: "dr-n-mathavan",
    name: "Dr. N. Mathavan",
    desig: "Assistant Professor",
    qual: "B.Tech - ECE, M.E, Ph.D",
    email: "memathavan@gmail.com",
    image: imgMathavan,
    spec: "IoT, Sensors, PLC",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-mathavan-nagaraj-045a06a8",
    about: "Dr. N. Mathavan is a dedicated faculty member with 13 years of teaching and research experience in the Department of Electronics and Communication Engineering. His areas of specialization include IoT, Sensors, and PLC. He is committed to fostering innovation through research, industry-oriented learning, and mentoring students in emerging electronics and automation technologies.",
    publications: ["12"],
    projects: ["1"],
    patents: ["2"],
    awards: ["2"],
    experience: ["13 Years"]
  },
  {
    id: "mr-m-idhayachandran",
    slug: "mr-m-idhayachandran",
    name: "Mr. M. Idhayachandran",
    desig: "Assistant Professor",
    qual: "B.E - ECE, M.E - VLSI Design",
    email: "idhayachandran@nscet.org",
    image: imgIdhayachandran,
    spec: "VLSI Design",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/idhayachandran-ece-a325562a3",
    about: "Idhaya Chandran M is a dedicated faculty member with 15 years of teaching and research experience in the Department of Electronics and Communication Engineering. His specialization is VLSI Design, and he is committed to helping students develop strong technical knowledge through practical learning while contributing to research and innovation in semiconductor and digital electronics technologies.",
    publications: ["4"],
    projects: ["10"],
    patents: [],
    awards: [],
    experience: ["15 Years"]
  },
  {
    id: "mr-s-prathap",
    slug: "mr-s-prathap",
    name: "Mr. S. Prathap",
    desig: "Assistant Professor",
    qual: "B.E - ECE, M.E - Communication Systems",
    email: "prathaps@nscet.org",
    image: imgPrathap,
    spec: "Embedded Systems & IoT Hardware",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/nscet",
    about: "Mr. S. Prathap is a dedicated faculty member in the Department of Electronics and Communication Engineering specializing in Communication Systems and Embedded Hardware.",
    publications: ["1"],
    projects: ["1"],
    patents: [],
    awards: [],
    experience: ["5 Years"]
  },
  {
    id: "mr-r-pradeep-kumar",
    slug: "mr-r-pradeep-kumar",
    name: "Mr. R. Pradeep Kumar",
    desig: "Assistant Professor",
    qual: "B.E - ECE, M.E - Applied Electronics",
    email: "pradeepkumar@nscet.org",
    image: imgPradeepKumar,
    spec: "Digital System Design",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/pradeep-kumar-ramaraj-93716778",
    about: "Pradeep Kumar R is a dedicated faculty member with 18 years of teaching and research experience in the Department of Electronics and Communication Engineering. His specialization is Digital System Design. With significant contributions in academic projects, research, and innovation, he is committed to mentoring students and fostering excellence in digital electronics and embedded system technologies.",
    publications: ["1"],
    projects: ["18"],
    patents: [],
    awards: [],
    experience: ["18 Years"]
  },
  {
    id: "mrs-t-tamilselvi",
    slug: "mrs-t-tamilselvi",
    name: "Mrs. T. Tamilselvi",
    desig: "Assistant Professor",
    qual: "B.E - ECE, M.Tech - VLSI Design",
    email: "tamilselvi@nscet.org",
    image: imgTamilSelvi,
    spec: "VLSI Design, Communication Systems",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/tamilselvi-t-a18a563b7",
    about: "Tamilselvi T is a dedicated faculty member in the Department of Electronics and Communication Engineering with a specialization in VLSI Design. She is passionate about semiconductor technologies, research, and helping students develop strong technical knowledge through innovative and practical learning.",
    publications: ["1"],
    projects: ["3"],
    patents: [],
    awards: [],
    experience: ["1 Year"]
  },
  {
    id: "mrs-p-shantha-devi",
    slug: "mrs-p-shantha-devi",
    name: "Mrs. P. Shantha Devi",
    desig: "Assistant Professor",
    qual: "B.E - ECE, M.E - VLSI Design",
    email: "shanthadevi@nscet.org",
    image: imgShanthaDevi,
    spec: "VLSI Design",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/shanthadevi-p-6a97803b8",
    about: "Shantha Devi P is a faculty member in the Department of Electronics and Communication Engineering with a specialization in VLSI Design. She is passionate about digital circuits, research, and helping students develop practical skills in semiconductor technology and VLSI systems.",
    publications: ["1"],
    projects: ["2"],
    patents: [],
    awards: [],
    experience: ["3 Years"]
  },
  {
    id: "mrs-a-gowthami",
    slug: "mrs-a-gowthami",
    name: "Mrs. A. Gowthami",
    desig: "Assistant Professor",
    qual: "B.E - ECE, M.E - Communication Systems",
    email: "gowthami@nscet.org",
    image: imgGowthami,
    spec: "Communication Systems",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/gowthami-anbalagan-a0212b126",
    about: "Gowthami A is a faculty member in the Department of Electronics and Communication Engineering with a specialization in Communication Systems. She is dedicated to teaching, research, and guiding students in wireless communications and signal processing technologies.",
    publications: ["1"],
    projects: ["1"],
    patents: [],
    awards: [],
    experience: ["2 Years"]
  },
  {
    id: "mr-k-bharathi-kannan",
    slug: "mr-k-bharathi-kannan",
    name: "Mr. K. Bharathi Kannan",
    desig: "Assistant Professor",
    qual: "B.E - ECE, M.E - VLSI Design",
    email: "bharathikannan@nscet.org",
    image: imgBharathiKannan,
    spec: "VLSI Design, Embedded Systems",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/nscet",
    about: "Mr. K. Bharathi Kannan is an Assistant Professor in the Department of Electronics and Communication Engineering specializing in VLSI Design and Embedded Systems.",
    publications: [],
    projects: [],
    patents: [],
    awards: [],
    experience: ["4 Years"]
  }
];
