import imgVembathuRajesh from "./images/vembathurajesh.png";
import imgDavidMathan from "./images/davidmathan.jpg";
import imgSaravanakumar from "./images/Saravakumar.png";
import imgSrinithi from "./images/Chemistry - Srinithi.jpeg";
import imgDeviMeenakshi from "./images/1778918990_Chemistry - Devi Meenakshi.jpg";
import imgSumathra from "./images/1778919066_Chemistry - Sumathra.jpeg";
import imgMalarvizhi from "./images/malarvizhi.jpg";
import imgSelvapriya from "./images/Selvapriya.jpg";
import imgValarmathi from "./images/Valarmathi.jpg";
import imgSangeetha from "./images/1778919146_English - Sangeetha.jpeg";
import imgChithra from "./images/Dr.C.CHITHRA.jpg";
import imgMallaiyasamy from "./images/mailysamy.jpg";
import imgMurugan from "./images/1778919261_Maths - Murugan.jpeg";
import imgBuvaneshwari from "./images/Buvaneswarih.jpg";
import imgDiana from "./images/Physics - Diana.jpg";
import imgEaswari from "./images/1778919497_Physics - Easwari.jpeg";
import imgKrishnamoorthi from "./images/krishnamoorthy.jpg";
import imgAntoChristy from "./images/AntoChristy.jpg";
import imgThisha from "./images/thisha.jpeg";
import imgPremkumar from "./images/General Engg - Premkumar.jpg";
import imgRamKumar from "./images/ramkumar.jpeg";
import imgRajeshshree from "./images/Rajeshshree.jpeg";
import imgArunkumar from "./images/arunkumar.jpg";
import imgJenifer from "./images/Jenifer Daksh.jpg";

export const shFacultyData = [
  {
    id: "hod",
    slug: "dr-a-vembathurajesh",
    name: "Dr. A. Vembathurajesh",
    desig: "Assistant Professor & Head [I/C] / S&H",
    qual: "B.E - Mechanical, M.E - Thermal, Ph.D - Mechanical",
    email: "vembathurajesh@nscet.org",
    image: imgVembathuRajesh,
    spec: "Materials, Thermal, Composites",
    objectPosition: "center 10%",
    isHOD: true,
    linkedin: "https://www.linkedin.com/in/dr-vembathurajesh-a-192b50426/",
    about: "Dr. A. Vembathurajesh is the Head of the Department with over 16 years of teaching and research experience in the Department of Science and Humanities. His areas of expertise include Materials, Thermal, and Composite Engineering. With numerous publications, research projects, patents, and academic achievements, he is dedicated to fostering innovation and excellence in engineering education.",
    publications: ["18"],
    projects: ["15"],
    patents: ["4"],
    awards: ["3"],
    experience: ["16+ Years"]
  },
  {
    id: "dr-n-david-mathan",
    slug: "dr-n-david-mathan",
    name: "Dr. N. David Mathan",
    desig: "Professor (Chemistry)",
    qual: "M.Sc, Ph.D",
    email: "davidmathan@nscet.org",
    image: imgDavidMathan,
    spec: "Flame Retardant Materials, Polymer Chemistry",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/david-mathan-n-6a83733ba",
    about: "Dr. N. David Mathan is a dedicated faculty member with 15 years of teaching and research experience in the Department of Science and Humanities. His areas of specialization include Flame Retardant Materials and Polymer Chemistry. He is passionate about scientific research, innovation, and mentoring students while contributing to advancements in materials science and chemistry.",
    publications: ["11"],
    projects: ["1"],
    patents: ["1"],
    awards: ["4"],
    experience: ["15 Years"]
  },
  {
    id: "dr-r-saravanakumar",
    slug: "dr-r-saravanakumar",
    name: "Dr. R. Saravanakumar",
    desig: "Associate Professor (Chemistry)",
    qual: "M.Sc., Ph.D.",
    email: "saravanakumar@nscet.org",
    image: imgSaravanakumar,
    spec: "Chemistry",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/saravana-kumar-741a343b7",
    about: "R. Saravanakumar is a dedicated faculty member with 14 years of teaching experience in the Department of Science and Humanities. His specialization is Chemistry, and he is passionate about academic excellence, research, and mentoring students through engaging and practical learning.",
    publications: ["4"],
    projects: [],
    patents: [],
    awards: [],
    experience: ["14 Years"]
  },
  {
    id: "dr-s-srinithi",
    slug: "dr-s-srinithi",
    name: "Dr. S. Srinithi",
    desig: "Assistant Professor (Chemistry)",
    qual: "B.Sc., M.Sc., Ph.D",
    email: "srinithi@nscet.org",
    image: imgSrinithi,
    spec: "Organic Chemistry",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-s-srinithi-7a5499245",
    about: "Dr. S. Srinithi is an Assistant Professor in the Department of Science and Humanities with a specialization in Organic Chemistry.",
    publications: ["2"],
    projects: ["1"],
    patents: [],
    awards: [],
    experience: ["4 Years"]
  },
  {
    id: "dr-s-devimeenakshmi",
    slug: "dr-s-devimeenakshmi",
    name: "Dr. S. Devimeenakshmi",
    desig: "Assistant Professor (Chemistry)",
    qual: "B.Sc., M.Sc., Ph.D",
    email: "devimeenakshi@nscet.org",
    image: imgDeviMeenakshi,
    spec: "Inorganic Chemistry & Nanotechnology",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-s-devimeenakshmi-56747514a",
    about: "Dr. S. Devimeenakshmi is a dedicated faculty member in the Department of Science and Humanities specializing in Chemistry.",
    publications: ["6"],
    projects: ["2"],
    patents: ["1"],
    awards: ["1"],
    experience: ["6 Years"]
  },
  {
    id: "dr-m-sumathra",
    slug: "dr-m-sumathra",
    name: "Dr. M. Sumathra",
    desig: "Assistant Professor (Chemistry)",
    qual: "B.Sc., M.Sc., Ph.D",
    email: "sumathra@nscet.org",
    image: imgSumathra,
    spec: "Physical Chemistry",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/sumathra-m-b60b543b7",
    about: "Dr. M. Sumathra is an Assistant Professor in the Department of Science and Humanities specializing in Chemistry.",
    publications: ["3"],
    projects: ["1"],
    patents: [],
    awards: [],
    experience: ["5 Years"]
  },
  {
    id: "dr-p-malarvizhi",
    slug: "dr-p-malarvizhi",
    name: "Dr. P. Malarvizhi",
    desig: "Assistant Professor (English)",
    qual: "M.A., M.Phil., Ph.D.",
    email: "malarvizhi@nscet.org",
    image: imgMalarvizhi,
    spec: "English Literature & ELT",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-malarvizhi-p-590b503b7",
    about: "Dr. P. Malarvizhi is an Assistant Professor in the Department of Science and Humanities with extensive experience in English Language Teaching.",
    publications: ["5"],
    projects: ["1"],
    patents: [],
    awards: ["2"],
    experience: ["11 Years"]
  },
  {
    id: "dr-s-selvapriya",
    slug: "dr-s-selvapriya",
    name: "Dr. S. Selvapriya",
    desig: "Assistant Professor (English)",
    qual: "M.A., M.Phil., Ph.D.",
    email: "selvapriya@nscet.org",
    image: imgSelvapriya,
    spec: "Comparative Literature, ELT",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-s-selvapriya-397274154",
    about: "Dr. S. Selvapriya is an Assistant Professor in the Department of Science and Humanities specializing in English Literature.",
    publications: ["4"],
    projects: [],
    patents: [],
    awards: ["1"],
    experience: ["8 Years"]
  },
  {
    id: "mrs-v-sangeetha",
    slug: "mrs-v-sangeetha",
    name: "Mrs. V. Sangeetha",
    desig: "Assistant Professor (English)",
    qual: "B.A., M.A., English (NET)",
    email: "vijayansangeetha281985@gmail.com",
    image: imgSangeetha,
    spec: "English Phonetics & Grammar",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/sangeetha-v-29a54b3b7",
    about: "Mrs. V. Sangeetha is an Assistant Professor in English in the Department of Science and Humanities.",
    publications: ["2"],
    projects: [],
    patents: [],
    awards: [],
    experience: ["4 Years"]
  },
  {
    id: "dr-r-valarmathi",
    slug: "dr-r-valarmathi",
    name: "Dr. R. Valarmathi",
    desig: "Assistant Professor (English)",
    qual: "B.A., M.A., Ph.D - English",
    email: "valarmathi@nscet.org",
    image: imgValarmathi,
    spec: "English Literature & Communication",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/nscet",
    about: "Dr. R. Valarmathi is an Assistant Professor in the Department of Science and Humanities specializing in English.",
    publications: [],
    projects: [],
    patents: [],
    awards: [],
    experience: []
  },
  {
    id: "dr-c-chithra",
    slug: "dr-c-chithra",
    name: "Dr. C. Chithra",
    desig: "Professor (Mathematics)",
    qual: "M.Sc, Ph.D",
    email: "chithra.c@nscet.org",
    image: imgChithra,
    spec: "Graph Theory",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-chithra-venkatesan-2039122b3",
    about: "Dr. C. Chithra is an experienced faculty member with over 23 years of teaching expertise in the Department of Science and Humanities. Specializing in Graph Theory, she is committed to quality education, academic research, and mentoring students toward excellence.",
    publications: ["4"],
    projects: [],
    patents: [],
    awards: ["2"],
    experience: ["23 Years 10 Months"]
  },
  {
    id: "dr-b-mallaiyasamy",
    slug: "dr-b-mallaiyasamy",
    name: "Dr. B. Mallaiyasamy",
    desig: "Associate Professor (Mathematics)",
    qual: "M.Sc, M.Phil",
    email: "mallaiyasamy@nscet.org",
    image: imgMallaiyasamy,
    spec: "Algebra, Operations Research",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/mallaiyasamy-b-7a2b533b7",
    about: "Dr. B. Mallaiyasamy is an Associate Professor in the Department of Science and Humanities with extensive experience in Mathematics and Operations Research.",
    publications: ["8"],
    projects: ["1"],
    patents: [],
    awards: ["1"],
    experience: ["18 Years"]
  },
  {
    id: "mr-m-murugan",
    slug: "mr-m-murugan",
    name: "Mr. M. Murugan",
    desig: "Assistant Professor (Mathematics)",
    qual: "B.Sc., M.Sc – Maths (SET)",
    email: "murugan@nscet.org",
    image: imgMurugan,
    spec: "Applied Mathematics",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/murugan-m-6a0b523b7",
    about: "Mr. M. Murugan is an Assistant Professor in the Department of Science and Humanities specializing in Mathematics.",
    publications: ["2"],
    projects: [],
    patents: [],
    awards: [],
    experience: ["5 Years"]
  },
  {
    id: "dr-r-bhuvaneshwari",
    slug: "dr-r-bhuvaneshwari",
    name: "Dr. R. Bhuvaneshwari",
    desig: "Assistant Professor (Physics)",
    qual: "B.Sc., M.Sc., Ph.D.",
    email: "bhuvaneshwari@nscet.org",
    image: imgBuvaneshwari,
    spec: "Crystal Growth & Materials Science",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-r-bhuvaneshwari-186985168",
    about: "Dr. R. Bhuvaneshwari is an Assistant Professor in the Department of Science and Humanities specializing in Physics.",
    publications: ["7"],
    projects: ["2"],
    patents: ["1"],
    awards: ["2"],
    experience: ["9 Years"]
  },
  {
    id: "dr-p-diana",
    slug: "dr-p-diana",
    name: "Dr. P. Diana",
    desig: "Assistant Professor (Physics)",
    qual: "B.Sc., M.Sc., Ph.D",
    email: "diana@nscet.org",
    image: imgDiana,
    spec: "Thin Films & Solar Cells",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-p-diana-3507a2164",
    about: "Dr. P. Diana is an Assistant Professor in the Department of Science and Humanities specializing in Physics and Material Science.",
    publications: ["5"],
    projects: ["1"],
    patents: [],
    awards: ["1"],
    experience: ["6 Years"]
  },
  {
    id: "dr-m-easwari",
    slug: "dr-m-easwari",
    name: "Dr. M. Easwari",
    desig: "Assistant Professor (Physics)",
    qual: "B.Sc., M.Sc., Ph.D",
    email: "easwari@nscet.org",
    image: imgEaswari,
    spec: "Nano Materials & Condensed Matter Physics",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/easwari-m-8b0b513b7",
    about: "Dr. M. Easwari is an Assistant Professor in the Department of Science and Humanities specializing in Physics.",
    publications: ["4"],
    projects: [],
    patents: [],
    awards: [],
    experience: ["5 Years"]
  },
  {
    id: "dr-s-r-krishnamoorthi",
    slug: "dr-s-r-krishnamoorthi",
    name: "Dr. S. R. Krishnamoorthi",
    desig: "Associate Professor (Physics)",
    qual: "M.Sc., M.Phil., Ph.D., MISTE",
    email: "krishnamoorthi@nscet.org",
    image: imgKrishnamoorthi,
    spec: "Solid State Physics",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-s-r-krishnamoorthi-1b2a533b7",
    about: "Dr. S. R. Krishnamoorthi is an Associate Professor in Physics in the Department of Science and Humanities with over 16 years of academic experience.",
    publications: ["10"],
    projects: ["2"],
    patents: ["1"],
    awards: ["3"],
    experience: ["16 Years"]
  },
  {
    id: "dr-p-anto-christy",
    slug: "dr-p-anto-christy",
    name: "Dr. P. Anto Christy",
    desig: "Assistant Professor (Physics)",
    qual: "M.Sc., Ph.D.",
    email: "antochristy@nscet.org",
    image: imgAntoChristy,
    spec: "Applied Physics",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/nscet",
    about: "Dr. P. Anto Christy is an Assistant Professor in the Department of Science and Humanities specializing in Physics.",
    publications: [],
    projects: [],
    patents: [],
    awards: [],
    experience: []
  },
  {
    id: "mrs-n-thisha",
    slug: "mrs-n-thisha",
    name: "Mrs. N. Thisha",
    desig: "Assistant Professor (Tamil)",
    qual: "B.A., M.A., NET",
    email: "thisha@nscet.org",
    image: imgThisha,
    spec: "Tamil Literature & Heritage",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/thisha-n-5b1b503b7",
    about: "Mrs. N. Thisha is an Assistant Professor of Tamil in the Department of Science and Humanities.",
    publications: ["2"],
    projects: [],
    patents: [],
    awards: [],
    experience: ["3 Years"]
  },
  {
    id: "dr-s-premkumar",
    slug: "dr-s-premkumar",
    name: "Dr. S. Premkumar",
    desig: "Assistant Professor (General Engg)",
    qual: "B.E, M.E, Ph.D",
    email: "premkumar@nscet.org",
    image: imgPremkumar,
    spec: "General Engineering & Water Resources",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/dr-premkumar-s-06a70640",
    about: "Dr. S. Premkumar is an Assistant Professor in the Department of Science and Humanities specializing in General Engineering and Civil subjects.",
    publications: ["5"],
    projects: [],
    patents: [],
    awards: [],
    experience: ["12.7 Years"]
  },
  {
    id: "mr-k-ram-kumar",
    slug: "mr-k-ram-kumar",
    name: "Mr. K. Ram Kumar",
    desig: "Assistant Professor (General Engg)",
    qual: "B.E - EEE, M.B.A",
    email: "ramkumar@nscet.org",
    image: imgRamKumar,
    spec: "General Engineering & Electrical Fundamentals",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/ramkumar-k-7a0b513b7",
    about: "Mr. K. Ram Kumar is an Assistant Professor in the Department of Science and Humanities specializing in General Engineering.",
    publications: ["1"],
    projects: ["1"],
    patents: [],
    awards: [],
    experience: ["5 Years"]
  },
  {
    id: "mrs-s-rajeshshree",
    slug: "mrs-s-rajeshshree",
    name: "Mrs. S. Rajeshshree",
    desig: "Assistant Professor (General Engg)",
    qual: "B.E - ECE, M.E",
    email: "rajeshshree@nscet.org",
    image: imgRajeshshree,
    spec: "General Engineering & Electronics Fundamentals",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/rajeshshree-s-4a1b523b7",
    about: "Mrs. S. Rajeshshree is an Assistant Professor in the Department of Science and Humanities specializing in General Engineering.",
    publications: ["1"],
    projects: [],
    patents: [],
    awards: [],
    experience: ["3 Years"]
  },
  {
    id: "mr-g-arunkumar",
    slug: "mr-g-arunkumar",
    name: "Mr. G. Arunkumar",
    desig: "Assistant Professor (General Engg)",
    qual: "B.E - Mechanical, M.E - Manufacturing",
    email: "arunkumar@nscet.org",
    image: imgArunkumar,
    spec: "General Engineering & Mechanical Fundamentals",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/arun-kumar-5433553b4",
    about: "Mr. G. Arunkumar is an Assistant Professor in the Department of Science and Humanities specializing in General Engineering.",
    publications: ["1"],
    projects: ["4"],
    patents: ["1"],
    awards: ["1"],
    experience: ["9 Years"]
  },
  {
    id: "mrs-k-jenifer",
    slug: "mrs-k-jenifer",
    name: "Mrs. K. Jenifer",
    desig: "Assistant Professor (General Engg)",
    qual: "B.E, M.E",
    email: "jenifer@nscet.org",
    image: imgJenifer,
    spec: "General Engineering",
    objectPosition: "center 10%",
    linkedin: "https://www.linkedin.com/in/jenifer-k-3b0b533b7",
    about: "Mrs. K. Jenifer is an Assistant Professor in the Department of Science and Humanities specializing in General Engineering.",
    publications: ["1"],
    projects: [],
    patents: [],
    awards: [],
    experience: ["3 Years"]
  }
];
